// src/router/pageTitles.js
const pageTitles = {
  home: 'ホーム',
  about: 'About',
  clientInfo: '閲覧環境',
  textHash: 'テキストハッシュ',
  videoToGif: 'ビデオからGIFへ',
  jsonFormatter: 'JSON整形',
  xmlFormatter: 'XML整形',
  textCaseConverter: 'テキストケース変換',
  countdownToHolidays: '祝日タイマー',
  worldTimezone: '世界時計',
  timezoneConverter: 'タイムゾーン変換',
  japaneseEra: '和暦',
  timeIssues: 'コンピュータ時刻問題',
  timeProgress: '時間進捗バー',
  escapeSequenceInterpreter: '制御文字展開',
  regexTester: '正規表現テスター',
  templateBaseRandomGenerator: 'ランダム文字列生成',
  uuidGenerator: 'UUID生成',
  textCounter: '文字数カウンター',
  unixTimeConverter: 'UNIXTIME変換',
  birthdateInfo: '誕生日情報',
  rubyGenerator: 'ルビ生成',
  lengthConverter: '距離単位変換',
  weightConverter: '重さ単位変換',
  areaConverter: '面積単位変換',
  volumeConverter: '体積単位変換',
  temperatureConverter: '温度単位変換',
  dataSizeConverter: 'データ量単位変換',
  durationConverter: '期間単位変換',
  textStyler: '文字装飾',
  imageMetadata: 'EXIF削除',
  sosu: '素数カウンター',
  blueskyShortcodes: 'Hugo埋め込みコード生成',
};

export default pageTitles;
